# Generated by Django 3.0.5 on 2021-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegdNo', models.CharField(max_length=10, unique=True)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Branch', models.CharField(max_length=30)),
                ('Batch', models.CharField(max_length=10)),
                ('Section', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherId', models.CharField(max_length=15, unique=True)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Branch', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
