# Generated by Django 3.0.5 on 2021-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(max_length=40),
        ),
    ]
