# Generated by Django 3.0.5 on 2021-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveAttendance', '0002_auto_20210424_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Branch',
            field=models.CharField(max_length=40),
        ),
    ]
