# Generated by Django 3.0.5 on 2021-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encodings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegdNo', models.CharField(max_length=20, unique=True)),
                ('Encoding', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='uploadfile',
        ),
    ]
